### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by eqprog** [sonic41592/ImgAlign#2]
Can you update the release version to include the latest code? The release code doesn't work.

**Comment by wdsongama** [comment]
@eqprog did you manage to run it?

**Comment by sonic41592** [comment]
Everything should be working now, almost everything has been rewritten and the release .exe matches the python code

**Comment by wdsongama** [comment]
I had not renamed the folders to HR and LR, guess that was the problem. It is working now.

**Comment by sonic41592** [comment]
Great, you can also specify any folder without having to rename them or even being in the same directory with the options -l and -g, just run -h for more info.

**Comment by wdsongama** [comment]
Does ImgAlign scale option supoort non-integer values? Because my LR images are 854x480, while the HR ones are 1920x1080, so the difference in scale between them is 2.25. If not, what should I do? Resize either the LR or HR images to an integer scale?

**Comment by sonic41592** [comment]
It does all the resizing for you, just put in your images as is. You specify the mode to use with -m which in most cases you would want to use -m 0 so that the LRs remain the same and the HRs are adjusted. I assume you're making a 2x dataset, so you would use -s 2 for the scale
